### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Jayan-K-Duggal** [ducha-aiki/LSUV-pytorch#1]
How can I use LSUV instead of Xavier in my NN, please let me know if I can implement it like this or is there any other way: 
LSUVinit(model, m.weight)
Can i use weights as my data or it will take images or any other form of data 
**ERROR** 
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[16, 64, 1, 1] to have 3 channels, but got 64 channels instead

**Comment by ducha-aiki** [comment]
No, you cannot use weights instead of training data. The idea of LSUV initialization is based on using data for init

**Comment by Jayan-K-Duggal** [comment]
what kind of data we have to use i.e images, transforms of images, or tensors of images ??

**Comment by ducha-aiki** [comment]
First batch of data, which you use in the training loop.
E.g. in example here https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html

`outputs = net(inputs)`

"inputs" is data you need.

**Comment by Jayan-K-Duggal** [comment]
I implemented it and now i am getting this error:


  File "/home/iot/Jayan/SqueezeNext/Py/LSUV.py", line 104, in LSUVinit
    cuda = data.is_cuda

AttributeError: 'function' object has no attribute 'is_cuda'

**Comment by ducha-aiki** [comment]
Which version of pytorch do you use? This repo was written for 0.3
